In [8]:
import numpy as np

In [46]:
def compute_ndcg_k(results, lstOriginalRank, k):
    m = 0.0
    _start = 0
    for tmp in lstOriginalRank:
        _end = _start + len(tmp)
        # те номера, которые поставили в топ к
        lstsorted = np.argsort(results[_start:_end])[:k]
        print(lstsorted)
        print(tmp)
        d = sum(np.array([tmp[lstsorted[i]] for i in range(k)]) / np.array([np.log2(i+1) for i in range(1, k + 1)])) \
                    / sum([1/np.log2(i+1) for i in range(1, k + 1)])
        m += d
        _start = _end 
    return m / len(lstOriginalRank)

In [47]:
compute_ndcg_k(results, lstOriginalRank, 5)

[0 1 2 6 3]
[1 1 1 1 1 1 0 0 0 0]


0.8539316501572937

In [28]:
results = np.array([0.1, 0.1, 0.1, 0.55, 0.6, 0.99, 0.2, 0.9, 0.9, 0.9])
lstOriginalRank = np.array([[1, 1, 1, 1, 1, 1, 0, 0, 0, 0]])

In [13]:
results * lstOriginalRank / 

array([0, 1, 1, 0, 1, 1, 0, 0, 0, 0])

In [49]:
sum([1/np.log2(i+1) for i in range(1, 5 + 1)])

2.9484591188793923